### ISSUE TITLE
Some emojis use regular ASCII characters, which causes ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by gthvidsten** [FrenchW/FrwTwemoji#10]
[This is a tweet](https://twitter.com/F1/status/883690097962614784) with a special emoji. The text `2\ufe0f\u20e3` is properly caught by the regular expression copied from Twemoji, but because it starts with the regular character `'2'`, the call to `char.ConvertToUtf32(char, char)` fails with an `ArgumentOutOfRangeException` with the message `A valid high surrogate character is between 0xd800 and 0xdbff, inclusive`.

`'2'` (or the value 0x32) is definitely outside 0xd800 and 0xdbff

This happens on line 267 in Generator/Helpers.cs

As you can see by the tweet on Twitter, they have correctly replaced `2\ufe0f\u20e3` with an emoji (with the codepoint `32-20e3`), whereas FrwTwemoji will end up using an "SOS" emoji (because an exception occured)

**Comment by FrenchW** [comment]
Sorry, I've been busy and forgot your issue
I'll have a look now
Thanks

**Comment by FrenchW** [comment]
Looks better now : 
![capture d ecran 2017-07-21 a 09 47 00](https://user-images.githubusercontent.com/36575/28453925-88bc86ac-6df9-11e7-90a4-73423e35b941.png)

**Comment by gthvidsten** [comment]
Looks much better 👍  Thank you :)
